linters:
  StringQuotes:
    enabled: false
  Shorthand:
    enabled: false
  PropertySortOrder:
    enabled: false
  IdSelector:
    enabled: false
  QualifyingElement:
    enabled: false
exclude: public/sass/elements/_reset.scss
  
